name: Tests

on:

  create:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  node-unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Current LTS version: v14
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node-${{ matrix.node-version }}
          path-to-lcov: build/coverage/library-node/lcov.info
          parallel: true


  browser-unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm install grunt-cli -g
      - run: grunt ci
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: browsers
          path-to-lcov: build/coverage/library/lcov/lcov.info
          parallel: true


  finish:
    needs:
      - node-unit-tests
      - browser-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true


  deploy:

    needs:
      - node-unit-tests
      - browser-unit-tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Publish NPM 📦
        run: npm publish --access public
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
